import type { AssessmentQuestion } from "./types.ts";

/** The same four questions appear for every respondent. Wording is a draft
 * from the assessment design discussion and needs respondent testing. */
export const openingQuestions: readonly AssessmentQuestion[] = [
  {
    id: "q1",
    kind: "multiple",
    maxSelections: 2,
    text: "Which areas have created the most difficulty for your organization recently?",
    helper: "Choose up to two. Think about the past three months.",
    source: "fixed",
    options: [
      { id: "decisions", text: "Getting decisions made or approvals completed." },
      { id: "authority", text: "Knowing who is responsible and who has authority to act." },
      { id: "relationships", text: "Working effectively across the board, leadership, staff, or partners." },
      { id: "values", text: "Putting agreed values and expectations into everyday practice." },
      { id: "demand", text: "Keeping up with demand, growth, or expansion." },
      { id: "workload", text: "Managing workload, staffing gaps, or recurring exhaustion." },
      { id: "funding", text: "Funding ongoing work and planning beyond current grants." },
      { id: "requirements", text: "Keeping up with requirements, reporting, or preparing for unexpected events." },
      { id: "key_person", text: "Keeping work moving when a key person is unavailable or leaves." },
      { id: "strategy", text: "Turning shared priorities and plans into coordinated action." },
      { id: "technology", text: "Making technology or AI useful and manageable." },
      { id: "other", text: "Something else." },
      { id: "none", text: "No significant difficulty at the moment." },
      { id: "unsure", text: "I’m not sure." },
    ],
  },
  {
    id: "q2",
    kind: "multiple",
    maxSelections: 2,
    text: "When work becomes difficult or pressure increases, how does your organization usually respond?",
    helper: "Choose up to two.",
    source: "fixed",
    options: [
      { id: "escalate", text: "More decisions and questions go to senior leadership." },
      { id: "extra_work", text: "People take on extra work or work longer hours." },
      { id: "wait_for_authority", text: "People wait while responsibility or authority is clarified." },
      { id: "separate_ways", text: "Different teams or individuals find their own ways forward." },
      { id: "postpone", text: "Planned work is postponed to handle immediate demands." },
      { id: "key_person", text: "Work depends on a particular person’s knowledge or relationships." },
      { id: "extra_checks", text: "Additional approvals, checks, or reporting are introduced." },
      { id: "agreed_process", text: "People adjust priorities and responsibilities through an agreed process." },
      { id: "varies", text: "The response varies too much to identify a usual pattern." },
      { id: "unsure", text: "I haven’t observed this / I’m not sure." },
    ],
  },
  {
    id: "q3",
    kind: "single",
    text: "Which consequence of these difficulties most needs attention now?",
    source: "fixed",
    options: [
      { id: "delay", text: "Important work or decisions are delayed." },
      { id: "wellbeing", text: "Staff wellbeing or retention is suffering." },
      { id: "service", text: "Service quality or reliability is affected." },
      { id: "leader_time", text: "Senior leadership has too little time for its main responsibilities." },
      { id: "finances", text: "Financial stability or future commitments are becoming uncertain." },
      { id: "safeguards", text: "Accountability, obligations, or safeguards are at risk." },
      { id: "focus", text: "Teams are losing focus or working toward competing priorities." },
      { id: "opportunity", text: "Growth, partnerships, or other opportunities are being held back." },
      { id: "other", text: "Another consequence." },
      { id: "little_impact", text: "There has been little or no noticeable impact." },
      { id: "unsure", text: "I’m not sure." },
    ],
  },
  {
    id: "q4",
    kind: "text",
    text: "Tell us about one recent situation that shows the difficulty you most want to address.",
    helper: "What happened, who was affected, and what changed or became harder? A few sentences are enough. Leave out names or confidential details.",
    source: "fixed",
  },
];
